# Generated by Django 3.0.2 on 2021-02-17 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import validators.validation


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20, validators=[validators.validation.nameValidation])),
                ('lastname', models.CharField(max_length=20)),
                ('contactNo', models.CharField(max_length=15, validators=[validators.validation.contactNoValidator])),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
