# Generated by Django 3.0.2 on 2021-02-17 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20210217_1715'),
        ('student', '0002_auto_20210217_1715'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issueDate', models.DateTimeField(auto_now_add=True)),
                ('returnDate', models.DateTimeField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book')),
                ('issueBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
