# Generated by Django 3.0.2 on 2021-03-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20210301_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookorder',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
